# ---
# jupyter:
#   jupytext:
#     text_representation:
#       extension: .py
#       format_name: light
#       format_version: '1.5'
#       jupytext_version: 1.16.0
#   kernelspec:
#     display_name: Python 3
#     language: python
#     name: python3
# ---

# # TCO Sensitivity Deep Dive
#
# **Main finding:** Labor variables (wage, overhead multiplier, headcount) each drive 5× more NPV
# swing than humanoid capex. Negotiating a better KV (collective agreement) tier or overhead
# structure matters more than hardware price.
#
# Data sources: `data/processed/sensitivity_oat_results.parquet`, `sensitivity_mc_samples.parquet`,
# `tco_scenarios.parquet` — all generated by `scripts/run_module_03.py`.

# ## 1. Setup

import pyarrow.parquet as pq
import matplotlib.pyplot as plt
import numpy as np
import collections

oat = pq.read_table("../data/processed/sensitivity_oat_results.parquet")
mc  = pq.read_table("../data/processed/sensitivity_mc_samples.parquet")
tco = pq.read_table("../data/processed/tco_scenarios.parquet")

PARAM_LABELS = {
    "humanoid_capex_eur":  "Humanoid Capex (€/unit)",
    "human_wage_eur":      "Labor Wage (€/hr)",
    "human_overhead_mult": "Labor Overhead Multiplier",
    "humanoid_count":      "Humanoid Count",
    "human_count":         "Human Count",
    "discount_rate":       "Discount Rate",
}

# ## 2. OAT Tornado: Dominant Drivers

# Build per-parameter NPV swing (max NPV - min NPV across the parameter's range)
params = oat.column("parameter").to_pylist()
npvs   = oat.column("npv_eur").to_pylist()

by_param = collections.defaultdict(list)
for p, n in zip(params, npvs):
    by_param[p].append(n)

swings = {
    PARAM_LABELS.get(p, p): max(v) - min(v)
    for p, v in by_param.items()
}
swings_sorted = sorted(swings.items(), key=lambda x: x[1])

fig, ax = plt.subplots(figsize=(8, 4))
labels = [s[0] for s in swings_sorted]
values = [s[1] / 1e3 for s in swings_sorted]  # in k€
bars = ax.barh(labels, values, color=["#2d6a9f" if v > 500 else "#aac4de" for v in values])
ax.set_xlabel("NPV Swing (k€, higher = more sensitive)")
ax.set_title("OAT Sensitivity: TCO drivers ranked by NPV impact")
ax.axvline(x=0, color="black", linewidth=0.5)
for bar, val in zip(bars, values):
    ax.text(val + 5, bar.get_y() + bar.get_height() / 2,
            f"€{val:.0f}k", va="center", fontsize=9)
plt.tight_layout()
plt.savefig("../reports/executive_charts/04_sensitivity_tornado.png", dpi=150, bbox_inches="tight")
plt.show()

# **Interpretation:** Wage, overhead multiplier, and headcount each produce a ~€1.2M swing in
# 5-year NPV when swept across their realistic ranges. Humanoid capex produces only a €240k swing —
# roughly 5× smaller. In Austrian logistics, collective agreement (KV) tier and overhead rate
# are the dominant cost levers, not the hardware price.

# ## 3. Monte Carlo Distribution

npv_mc = np.array(mc.column("npv_eur").to_pylist())
p5, p50, p95 = np.percentile(npv_mc, [5, 50, 95])

fig, ax = plt.subplots(figsize=(8, 3.5))
ax.hist(npv_mc / 1e3, bins=50, color="#2d6a9f", alpha=0.8, edgecolor="white", linewidth=0.3)
ax.axvline(p5 / 1e3,  color="#e05c1a", linestyle="--", label=f"P5  = €{p5/1e3:,.0f}k")
ax.axvline(p50 / 1e3, color="#f0a500", linestyle="--", label=f"P50 = €{p50/1e3:,.0f}k")
ax.axvline(p95 / 1e3, color="#3aaa35", linestyle="--", label=f"P95 = €{p95/1e3:,.0f}k")
ax.set_xlabel("5-Year NPV (k€)")
ax.set_ylabel("Frequency")
ax.set_title(f"Monte Carlo NPV Distribution (n=10,000)\nmean=€{npv_mc.mean()/1e3:,.0f}k  σ=€{npv_mc.std()/1e3:,.0f}k")
ax.legend(fontsize=9)
plt.tight_layout()
plt.show()

# **Interpretation:** The distribution is left-skewed — the downside tail (P5 = €-1.83M) is wider
# than the upside (P95 = €-460k vs baseline €-1.6M). This reflects the asymmetric risk profile:
# labor cost increases hurt more than humanoid capex reductions help.

# ## 4. Scenario Comparison

scenario_ids  = tco.column("scenario_id").to_pylist()
scenario_npvs = [v / 1e3 for v in tco.column("npv_eur").to_pylist()]

fig, ax = plt.subplots(figsize=(8, 3.5))
colors = ["#aac4de" if s == "S-baseline-human" else "#2d6a9f" for s in scenario_ids]
bars = ax.bar(scenario_ids, scenario_npvs, color=colors)
ax.set_ylabel("5-Year NPV (k€)")
ax.set_title("TCO by Scenario (lower = less costly)")
ax.tick_params(axis="x", rotation=15)
for bar, val in zip(bars, scenario_npvs):
    ax.text(bar.get_x() + bar.get_width() / 2, val - 25,
            f"€{val:,.0f}k", ha="center", va="top", fontsize=8, color="white")
plt.tight_layout()
plt.show()

# **Non-obvious finding:** S-hybrid-amr (€-924k) outperforms S-pure-humanoid (€-960k).
# Full humanoid replacement is *more expensive* than a human+AMR hybrid, because the AMR handles
# repetitive transport at lower capex while humans handle variable tasks. The automation sweet spot
# is not 100% — it is the mixed configuration that minimises total cost per order.

# ## 5. Key Takeaways
#
# | Finding | Implication |
# |---|---|
# | Labor overhead swing = 5× humanoid capex swing | Wage negotiations matter more than hardware deals |
# | P95 NPV = €-460k (vs baseline €-1.6M) | Best-case scenario achieves ~71% cost reduction |
# | S-hybrid-amr beats S-pure-humanoid by €36k/5yr | Full automation is not the optimum |
# | MC σ = €418k on a €924k NPV | Wide uncertainty band — assumptions drive the result |
#
# All numbers are model outputs from public assumptions. See `config/tco_assumptions.yaml`
# for sources and `docs/ADR/0007` for the simulation validation story.
