"""Generate the claims ledger from inline evidence tags."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_FILES = (REPO_ROOT / "README.md",)
TAG_RE = re.compile(r"<!--\s*claim:\s*(.*?)\s*-->", re.DOTALL)
REFERENCE_RE = re.compile(
    r"(?P<artifact>[^;\s]+?\.json)::(?P<path>[A-Za-z0-9_.\[\]-]+)"
    r"(?:\s*\[(?P<format>[A-Za-z0-9_-]+)\])?$"
)
PATH_PART_RE = re.compile(r"([A-Za-z_][A-Za-z0-9_]*)|\[(\d+)\]")


def _resolve_path(payload: object, path: str) -> object:
    """Resolve dotted keys and list indices from a JSON report."""
    value = payload
    for key, index in PATH_PART_RE.findall(path):
        if key:
            if not isinstance(value, dict):
                raise ValueError(f"Expected object before key {key!r}")
            value = value[key]
        else:
            if not isinstance(value, list):
                raise ValueError(f"Expected list before index {index}")
            value = value[int(index)]
    return value


def _format_value(value: object, format_name: str | None) -> str:
    if not isinstance(value, (int, float)):
        return json.dumps(value, sort_keys=True)
    if format_name == "eur":
        return f"€{value:,.0f}"
    if format_name == "eur_m":
        return f"€{abs(value) / 1_000_000:.3f}M"
    if format_name == "pct":
        return f"{value * 100 if abs(value) <= 1 else value:.1f}%"
    if format_name == "count":
        return f"{value:,}"
    return str(value)


def collect_claims() -> list[tuple[str, str, str, str]]:
    """Return deterministic ledger rows: location, evidence, value, status."""
    rows: list[tuple[str, str, str, str]] = []
    for source in SOURCE_FILES:
        for line_number, line in enumerate(
            source.read_text(encoding="utf-8").splitlines(), start=1
        ):
            for tag in TAG_RE.findall(line):
                for reference in tag.split(";"):
                    reference = reference.strip().removeprefix("claim:").strip()
                    if reference == "structural":
                        rows.append(
                            (
                                f"{source.relative_to(REPO_ROOT)}:{line_number}",
                                reference,
                                "—",
                                "structural",
                            )
                        )
                        continue
                    match = REFERENCE_RE.fullmatch(reference)
                    if match is None:
                        raise ValueError(
                            f"Invalid claim reference at {source}:{line_number}: {reference}"
                        )
                    artifact = REPO_ROOT / match["artifact"]
                    payload = json.loads(artifact.read_text(encoding="utf-8"))
                    value = _resolve_path(payload, match["path"])
                    rows.append(
                        (
                            f"{source.relative_to(REPO_ROOT)}:{line_number}",
                            reference,
                            _format_value(value, match["format"]),
                            "PASS",
                        )
                    )
    return rows


def render_ledger(rows: list[tuple[str, str, str, str]]) -> str:
    """Render a stable Markdown ledger."""
    lines = [
        "# Claims ledger",
        "",
        "Generated by `python scripts/generate_claims_ledger.py` from inline `claim` tags.",
        "",
        "| Location | Evidence reference | Recomputed value | Status |",
        "| --- | --- | --- | --- |",
    ]
    lines.extend(
        f"| {location} | `{evidence}` | {value} | {status} |"
        for location, evidence, value, status in rows
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=REPO_ROOT / "governance" / "CLAIMS_LEDGER.md",
        help="Path for the generated Markdown ledger.",
    )
    args = parser.parse_args()
    args.output.write_text(render_ledger(collect_claims()), encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
