"""Generate the assumption register from the two authoritative YAML configs."""

from __future__ import annotations

import argparse
import json
from collections.abc import Iterator
from pathlib import Path

import yaml
from _governance_check import REPO_ROOT
from check_config_consumption import _leaf_keys, uncovered_keys

CONFIGS = (
    REPO_ROOT / "config" / "tco_assumptions.yaml",
    REPO_ROOT / "config" / "autostore_baseline.yaml",
)
OUTPUT = REPO_ROOT / "governance" / "ASSUMPTION_REGISTER.md"


def _value_at(data: object, dotted_key: str) -> object:
    value = data
    for part in dotted_key.split("."):
        if not isinstance(value, dict):
            return None
        value = value.get(part)
    return value


def _format(value: object) -> str:
    if value is None:
        return "—"
    return json.dumps(value, ensure_ascii=False, separators=(", ", ": "))


def _escape(value: object) -> str:
    return _format(value).replace("|", "\\|")


def _sensitivity_for(key: str, config: dict) -> str:
    sensitivity = config.get("sensitivity", {})
    if not isinstance(sensitivity, dict):
        return "—"
    final_key = key.rsplit(".", maxsplit=1)[-1]
    matches: list[str] = []
    for method in ("oat", "monte_carlo", "base_point"):
        values = sensitivity.get(method, {})
        if isinstance(values, dict) and final_key in values:
            matches.append(method)
    return ", ".join(matches) if matches else "—"


def _range_or_distribution(key: str, config: dict) -> object:
    parent, _, leaf = key.rpartition(".")
    sibling_range = _value_at(config, f"{parent}.{leaf}_range" if parent else f"{leaf}_range")
    if sibling_range is not None:
        return sibling_range
    sensitivity = config.get("sensitivity", {})
    if isinstance(sensitivity, dict):
        for method in ("oat", "monte_carlo"):
            values = sensitivity.get(method, {})
            if isinstance(values, dict) and leaf in values:
                return values[leaf]
    return None


def _rows() -> Iterator[tuple[str, str, object, object, str, str, str, str]]:
    source_text = "\n".join(
        path.read_text(encoding="utf-8") for path in (REPO_ROOT / "src").rglob("*.py")
    )
    for config_path in CONFIGS:
        config = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
        if not isinstance(config, dict):
            continue
        declared = {
            entry["key"]: entry
            for entry in config.get("unmodeled_parameters", [])
            if isinstance(entry, dict) and isinstance(entry.get("key"), str)
        }
        for key in sorted(_leaf_keys(config)):
            final_key = key.rsplit(".", maxsplit=1)[-1]
            declaration = declared.get(key)
            if declaration:
                status = f"unmodeled ({declaration['bias']})"
                source = declaration["note"]
                source_class = "declared model gap"
            else:
                status = "modeled" if final_key in source_text else "unmodeled (unknown)"
                source = str(config_path.relative_to(REPO_ROOT))
                source_class = "configuration"
            yield (
                config_path.name,
                key,
                _value_at(config, key),
                _range_or_distribution(key, config),
                source,
                source_class,
                status,
                _sensitivity_for(key, config),
            )


def render() -> str:
    uncovered = uncovered_keys(CONFIGS, REPO_ROOT / "src")
    lines = [
        "# Assumption register",
        "",
        "> Generated by `python scripts/generate_assumption_register.py`; do not edit by hand.",
        "",
        "The register covers every non-scenario configuration leaf. `modeled` means the key's",
        "terminal name is consumed by source code; declared gaps retain their documented bias.",
        "",
        (
            "| Config | Key | Value | Range/distribution | Source | Source class | "
            "Status | Sensitivity |"
        ),
        "|---|---|---|---|---|---|---|---|",
    ]
    for row in _rows():
        lines.append("| " + " | ".join(_escape(value) for value in row) + " |")
    lines.extend(
        [
            "",
            (
                f"Generated from {len(CONFIGS)} YAML files. "
                f"Untriaged consumed-key gaps: {len(uncovered)}."
            ),
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(), encoding="utf-8")
    print(f"[PASS] generated {args.output}")


if __name__ == "__main__":
    main()
