"""Write a starter governance/SESSION_END.md for the next session to read.

Phase 0: writes a templated stub with current AUDIT_STATE summary. The operator
edits free-text fields (open questions, next priority) before committing.
Phase 3 adds prompts for interactive completion.
"""

from __future__ import annotations

import json
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
GOV = REPO_ROOT / "governance"
STATE_PATH = GOV / "AUDIT_STATE.json"
SESSION_END_PATH = GOV / "SESSION_END.md"


def _changed_files_since_session_start() -> list[str]:
    """Best-effort: list files changed in the working tree relative to HEAD."""
    try:
        out = subprocess.check_output(
            ["git", "diff", "--name-only", "HEAD"],  # noqa: S607
            cwd=REPO_ROOT,
            text=True,
        )
        return [line for line in out.splitlines() if line.strip()]
    except (subprocess.CalledProcessError, FileNotFoundError):
        return []


def main() -> int:
    if not STATE_PATH.exists():
        print("[session_end] run `make audit` first to refresh AUDIT_STATE.json", file=sys.stderr)
        return 1
    state = json.loads(STATE_PATH.read_text())
    summary = state.get("summary", {})
    changed = _changed_files_since_session_start()
    findings_touched = [c for c in changed if c.startswith("governance/findings/")]
    adrs_touched = [
        c for c in changed if c.startswith("governance/adrs/")
    ]
    scripts_touched = [
        c for c in changed if c.startswith("scripts/check_") or c.startswith("tests/governance/")
    ]
    now = datetime.now(UTC)
    counts_line = (
        f"total={summary.get('findings_total', 0)} · "
        f"open={summary.get('findings_open', 0)} · "
        f"in_progress={summary.get('findings_in_progress', 0)} · "
        f"closed={summary.get('findings_closed', 0)}"
    )
    body = f"""# Session End — {now.date().isoformat()}

> Generated by `make session-end` at {now.isoformat()}.
> Edit the free-text fields below before committing.

## Audit state at session end

- Findings: {counts_line}
- Migrations in_progress: {summary.get('migrations_in_progress', 0)}

## Findings touched this session

{chr(10).join('- ' + f for f in findings_touched) or '_(none in working tree)_'}

## ADRs added or modified

{chr(10).join('- ' + a for a in adrs_touched) or '_(none in working tree)_'}

## Invariants installed (scripts and tests)

{chr(10).join('- ' + p for p in scripts_touched) or '_(none in working tree)_'}

## Open questions for next session

_(edit me)_

## Recommended next-finding priority

_(edit me — pick a F-NNN with non-null verification_script)_

---
*Read by `make session-start` of the next session.*
"""
    SESSION_END_PATH.write_text(body)
    print(f"[session_end] wrote {SESSION_END_PATH.relative_to(REPO_ROOT)}")
    print("[session_end] edit the free-text fields before committing.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
