"""Generate governance/SESSION_HANDOUT.md from AUDIT_STATE.json + findings + last SESSION_END.

Phase 0: minimal-but-functional handout (open findings, in-progress migrations,
last-session pointer). Phase 3 adds richer prioritization and prior-session
state propagation.
"""

from __future__ import annotations

import json
import sys
from datetime import UTC, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
GOV = REPO_ROOT / "governance"
STATE_PATH = GOV / "AUDIT_STATE.json"
HANDOUT_PATH = GOV / "SESSION_HANDOUT.md"
SESSION_END_PATH = GOV / "SESSION_END.md"


def _format_findings(findings: list[dict], statuses: set[str]) -> str:
    rows = [f for f in findings if f["status"] in statuses]
    if not rows:
        return "_(none)_"
    rows.sort(key=lambda f: (f["status"], f["id"]))
    lines = ["| ID | Status | Category | Title |", "|---|---|---|---|"]
    for f in rows:
        lines.append(f"| {f['id']} | {f['status']} | {f['category']} | {f['title']} |")
    return "\n".join(lines)


def _format_migrations(migrations: list[dict]) -> str:
    if not migrations:
        return "_(none)_"
    lines = ["| Name | Status | Started | Max days | Linked finding |", "|---|---|---|---|---|"]
    for m in migrations:
        lines.append(
            f"| {m['name']} | {m['status']} | {m['started_at']} | "
            f"{m['max_days_in_progress']} | {m.get('linked_finding', '—')} |"
        )
    return "\n".join(lines)


def _recommend_next_action(summary: dict, migrations: list[dict]) -> str:
    if any(m["status"] == "in_progress" for m in migrations):
        return (
            "Continue any in_progress migration first (see table below) — these "
            "block progress on linked findings."
        )
    if summary.get("findings_open"):
        return (
            "Pick one `open` finding (lowest ID with non-null verification_script) "
            "and work as Remediator. See governance/AUDIT_PROCEDURE.md."
        )
    if summary.get("findings_in_progress"):
        return "Finish in_progress findings before opening new work."
    return "All findings closed. Run `make verify` to confirm Adversary state."


def main() -> int:
    if not STATE_PATH.exists():
        print(
            f"[session_start] {STATE_PATH.relative_to(REPO_ROOT)} missing — "
            f"run `make audit` first.",
            file=sys.stderr,
        )
        return 1
    state = json.loads(STATE_PATH.read_text())
    summary = state.get("summary", {})
    findings = state.get("findings", [])
    migrations = state.get("migrations", [])
    last_end = (
        SESSION_END_PATH.read_text().strip()
        if SESSION_END_PATH.exists()
        else "_(no prior SESSION_END.md found — this may be the first session)_"
    )
    now = datetime.now(UTC)
    open_table = _format_findings(findings, {"open", "in_progress"})
    in_progress_migrations = [m for m in migrations if m["status"] == "in_progress"]
    migrations_table = _format_migrations(in_progress_migrations)
    next_action = _recommend_next_action(summary, in_progress_migrations)
    findings_line = (
        f"total={summary.get('findings_total', 0)} · "
        f"open={summary.get('findings_open', 0)} · "
        f"in_progress={summary.get('findings_in_progress', 0)} · "
        f"closed={summary.get('findings_closed', 0)} · "
        f"historical={summary.get('findings_closed_historical', 0)} · "
        f"wont_fix={summary.get('findings_wont_fix', 0)}"
    )
    migrations_line = (
        f"total={summary.get('migrations_total', 0)} · "
        f"in_progress={summary.get('migrations_in_progress', 0)}"
    )
    sources_line = (
        "*Generated from: `governance/AUDIT_STATE.json` + "
        "`governance/findings/F-*.yaml` + `governance/SESSION_END.md` (prior).*"
    )

    body = f"""# Session Handout — {now.date().isoformat()}

> Auto-generated by `make session-start` at {now.isoformat()}.
> Do not hand-edit; re-run to refresh.

## Audit state at session start

- `AUDIT_STATE.json` generated_at: `{state.get('generated_at', 'unknown')}`
- git branch: `{state.get('git_branch', 'unknown')}`
- git HEAD: `{state.get('git_head_sha', 'unknown')[:12]}`
- Findings: {findings_line}
- Migrations: {migrations_line}

## Recommended next action

{next_action}

## Open and in-progress findings

{open_table}

## In-progress migrations

{migrations_table}

## Last session

{last_end}

---
{sources_line}
"""
    HANDOUT_PATH.write_text(body)
    print(f"[session_start] wrote {HANDOUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
