"""F-239 — locked uv install includes analytics where dbt runs."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def test_f239_lock_and_ci_include_analytics() -> None:
    lock = (ROOT / "uv.lock").read_text(encoding="utf-8")
    assert 'name = "dbt-duckdb"' in lock
    assert 'provides-extras = ["dev", "notebooks", "analytics"]' in lock

    req = (ROOT / "requirements.txt").read_text(encoding="utf-8")
    assert req.startswith("# This file was autogenerated by uv")
    assert "uv export" in req.splitlines()[1]
    assert "\x00" not in req  # not UTF-16

    makefile = (ROOT / "Makefile").read_text(encoding="utf-8")
    assert "uv sync --frozen --extra dev --extra analytics" in makefile

    pipeline = (ROOT / ".github" / "workflows" / "pipeline.yml").read_text(encoding="utf-8")
    assert "uv sync --frozen --extra dev --extra analytics" in pipeline
    assert "dbt build" in pipeline
    # analytics install appears before dbt in the modules job
    modules_block = pipeline.split("name: Run Pipeline", 1)[1]
    sync_pos = modules_block.find("uv sync --frozen --extra dev --extra analytics")
    dbt_pos = modules_block.find("dbt build")
    assert 0 <= sync_pos < dbt_pos

    ci = (ROOT / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
    assert "uv sync --frozen --extra dev --extra analytics" in ci
    assert 'uv pip install -e ".[dev,analytics]"' not in ci
