"""F-046 — cost-per-order executive chart must exist and be generated by module_04.

Ratchet pattern: xfails while open, hard-fails on regression after close.

Guards:
  1. reports/executive_charts/05_cost_per_order.png exists.
  2. src/.../pipelines/module_04_dashboards.py references the chart filename
     '05_cost_per_order.png' — prevents silent revert to old chart list.
  3. module_04_dashboards.py reads cost_per_order_eur from tco_scenarios parquet
     — prevents re-implementing with hard-coded values that drift from the
     pipeline output.
"""

from __future__ import annotations

import re

from _ratchet import REPO_ROOT, ratchet

CHART = REPO_ROOT / "reports" / "executive_charts" / "05_cost_per_order.png"
MODULE_04 = REPO_ROOT / "src" / "warehouse_humanoid_tco" / "pipelines" / "module_04_dashboards.py"
MIN_SIZE_BYTES = 10_000


def test_cost_per_order_chart_file_exists() -> None:
    if not CHART.exists() or CHART.stat().st_size < MIN_SIZE_BYTES:
        ratchet(
            "F-046",
            fixed=False,
            gap_msg=(
                f"{CHART.relative_to(REPO_ROOT)} "
                f"{'missing' if not CHART.exists() else f'too small ({CHART.stat().st_size}B)'}"
                " — run `make all` or `make presentation`"
            ),
        )
        return
    ratchet("F-046", fixed=True, gap_msg="")


def test_module_04_generates_cost_per_order_chart() -> None:
    if not MODULE_04.exists():
        ratchet("F-046", fixed=True, gap_msg="module_04_dashboards.py absent — vacuously fixed")
        return
    text = MODULE_04.read_text()
    has_filename = "05_cost_per_order.png" in text
    reads_column = bool(re.search(r"cost_per_order_eur", text))
    ratchet(
        "F-046",
        fixed=has_filename and reads_column,
        gap_msg=(
            f"module_04_dashboards.py: has_filename={has_filename} " f"reads_column={reads_column}"
        ),
    )
